### ISSUE TITLE
Add option to change thickness and text size of labels.

### ISSUE THREAD

**Issue by shoumikchow** [shoumikchow/bbox-visualizer#4]
The current size defaults aren't suitable for small images. Ideally, the user should have the option to change the size.

**Comment by kanchitank** [comment]
I would like to work on this.

**Comment by shoumikchow** [comment]
Hi, feel free to fork the repo and put in a PR!

**Comment by kanchitank** [comment]
#7

**Comment by shoumikchow** [comment]
Thanks for the PR! Please give me until this weekend to review and merge.

**Comment by Brianrmendes** [comment]
I'm currently working on this

**Comment by nefelipar** [comment]
> The current size defaults aren't suitable for small images. Ideally, the user should have the option to change the size.

Is it still open? I would like to work on this issue.

**Comment by nefelipar** [comment]
Is it still open? I would like to work on this issue.

**Comment by nefelipar** [comment]
@shoumikchow 
Is it still open? I would like to work on this issue.

**Comment by shoumikchow** [comment]
@nefelipar yes it is! feel free to put in a PR. Please follow the contribution guidelines.

**Comment by nefelipar** [comment]
@shoumikchow
Do you want the thickness and the text size to be requested from the user or in some other way?

**Comment by nefelipar** [comment]
@shoumikchow
Do you want the thickness and the text size to be requested from the user or with a button
I thought that I can put a button that will have some default settings, and if the user wants to change them, press it and put the values ​​he wants.

**Comment by shoumikchow** [comment]
@nefelipar The user should not be prompted for thickness and text size, nor should there be a button for it. Instead, the user should have the _option_ to change it if required. Ideally, the user should be able to use keyword arguments to change the default values.
Please refer to this incomplete PR: https://github.com/shoumikchow/bbox-visualizer/pull/7 for details.

**Comment by nefelipar** [comment]
@shoumikchow 
For the keyword arguments do you want to be functions where the user will change the parameters (or don't change them because they want to use the default values), or should I take the keyword arguments some other way? I saw 7 but that detail is not clear. Thanks a lot and sorry for the questions but I'm begginer.

**Comment by nefelipar** [comment]
@shoumikchow
For the keyword arguments do you want to be functions where the user will change the parameters (or don't change them because they want to use the default values), or should I take the keyword arguments some other way? I saw PR 7 but that detail is not clear. Thanks a lot and sorry for the questions but I'm begginer.

**Comment by nefelipar** [comment]
@shoumikchow 
Hello again.
Do you want me to add parameters to the functions he needs, which will have a default value and when the user wants different values he can change them by putting another value in the parameter?
Otherwise I can create new functions that will either not have any parameters and the size and thickness will take the default values, or there will be parameters that the user will change with the keyboard and these values will be defined as thickness and size.
Sorry for so many questions but I'm a beginner.
Τhank you very much!

**Comment by nefelipar** [comment]
@shoumikchow 
I have submitted a pull request.
Please check it out when you have the time. Thank you very much!

**Comment by shoumikchow** [comment]
Fiied by #17
