### ISSUE TITLE
Single function for drawing box which will take labelling style as parameter

### ISSUE THREAD

**Issue by shreyasvedpathak** [shoumikchow/bbox-visualizer#9]
**Is your feature request related to a problem? Please describe.**
When I tried using this package, I found it annoying to draw the box first and then decide on a labelling method. And it was again inconsistent incase of `draw_flag_with_label()`. 

**Describe the solution you'd like**
I had a suggestion, I think it would be easier and very pythonic if we could pass the labelling style as an argument to a function. 
Like this, 
```python
def draw_box(image, bbox, labelling_method="regular")
     ...
```
and the `labelling_method` argument can take `regular`, `t-style`, `flag`.

**Additional context**
None

**Comment by shreyasvedpathak** [comment]
As I faced this issue, I started working on it. If I reach a feasible solution, it will be great for other users as well. Of course, the documentation will have to be updated. If I have @shoumikchow your permission I can make the PR ASAP.

**Comment by shoumikchow** [comment]
Hi @shreyasvedpathak, thanks for the feature request. Separating the bounding box and the label was a conscious decision. There might be cases where a user only wants to draw the box and not label it.

You could argue that you could still add this function since you aren't removing those core methods. However, I think the number of functions in this library is already pretty high for the size of the code. Anything more would bloat the library. I don't think using two functions (one for drawing the box and another for labeling it) instead of the one you suggested is too difficult a task for users who would be working with object detection.

Therefore, I am closing this issue.

**Comment by shreyasvedpathak** [comment]
I agree with you, it's just some lines can be wrapped in a function and provide a higher level interface for doing the task. But I do get your point. Thanks. If in future if you think you want to implement this, I would be happy to contribute.
